---
# tasks file for apache
- name: Install apache httpd  (state=present is optional)
  apt:
        name: apache2
        state: present
        update_cache: yes
  tags: skip

- name: send template to apache2 service
  template:
        src: apache-ports.conf.j2
        dest: /etc/apache2/ports.conf
        backup: yes
  notify: restart

